### ISSUE TITLE
Split the callback interface to two interfaces (success and error)

### ISSUE THREAD

**Issue by anragab** [mikepenz/Storyblok-Android-SDK#1]
At the moment I can't reuse my error handling and I can't also shorten my callbacks to a pair of lambdas.

Sometimes errors should also be propagated without being handled if I choose to so error handling callback should also not be mandatory

Thanks!

**Comment by mikepenz** [comment]
@anragab nice thoughts. I would be more than happy about taking a PR to enhance this. 

Some side notes. The current project is not yet java compatible, but with a few tiny changes to this project it should be possible to build as an "*.jar" allowing this to be used also in java projects

**Comment by mikepenz** [comment]
@anragab too late :D included this change in v0.3.0
